name: Turbo Stats Refresh

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches: [ main ]

jobs:
  refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    - uses: actions/checkout@v4

    - name: Update timestamp
      run: date +%s > timestamp

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "🔄 Stats refresh trigger"
        file_pattern: timestamp
        skip_fetch: true
        branch: main
